# Generated by Django 4.1.4 on 2023-02-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lect_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lect_name', models.TextField()),
                ('lect_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('stud_name', models.TextField()),
                ('stud_phone', models.CharField(max_length=12)),
                ('mentor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateField()),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('int_lect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.lecturer')),
                ('int_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.student')),
            ],
        ),
    ]
