# Generated by Django 4.1.4 on 2023-02-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intervention', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='password',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.lecturer'),
        ),
    ]
