# Generated by Django 4.1.4 on 2023-02-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intervention', '0002_delete_login_lecturer_password_alter_student_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
