# Generated by Django 4.1.4 on 2023-02-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Intervention', '0007_remove_student_mentor_delete_intervention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lect_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lect_name', models.TextField()),
                ('lect_email', models.TextField()),
                ('department', models.CharField(max_length=3)),
                ('password', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('sev_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('sev_level', models.TextField()),
                ('sev_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('stud_name', models.TextField()),
                ('stud_phone', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=4)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('int_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_report', models.DateField()),
                ('description', models.TextField()),
                ('action', models.TextField()),
                ('category', models.TextField()),
                ('int_lect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.lecturer')),
                ('int_sev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.severity')),
                ('int_stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervention.student')),
            ],
        ),
    ]
